import com.sun.net.httpserver.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.MessageDigest;
import java.time.*;
import java.util.*;
import java.util.concurrent.Executors;

/** Document-driven restaurant control system: import sales, then calculate stock and profit. */
public class RestaurantManager {
    private record MenuItem(String name,double price,List<Recipe.Ingredient> recipe) {}
    private record ImportJob(String id,String filename,String hash,byte[] original,SalesImporter.Parsed parsed,Map<String,String> mapping,List<SalesImporter.Row> rows) {}
    private record PurchaseRow(LocalDate date,String ingredient,double quantity,double unitCost,double total,String supplier,String invoice,int sourceRow,List<String> errors) {}
    private record PurchaseJob(String id,String filename,String hash,byte[] original,SalesImporter.Parsed parsed,Map<String,String> mapping,List<PurchaseRow> rows) {}
    private static final Path DATA=Paths.get("data"),STOCK=DATA.resolve("inventory.csv"),IMPORTS=DATA.resolve("imports"),TX=DATA.resolve("inventory-transactions.csv"),SALES=DATA.resolve("imported-sales.csv"),WASTE=DATA.resolve("waste.csv"),HASHES=DATA.resolve("import-hashes.txt");
    private final Map<String,Inventory> stock=new LinkedHashMap<>();private final Map<String,MenuItem> menu=new LinkedHashMap<>();private final Map<String,String> aliases=new HashMap<>();private final Map<String,ImportJob> staged=new HashMap<>();private final Map<String,PurchaseJob> stagedPurchases=new HashMap<>();private final SupplierStore supplierStore;

    RestaurantManager()throws IOException{seed();supplierStore=new SupplierStore(DATA);}
    public static void main(String[]a){int p=a.length>0?Integer.parseInt(a[0]):8080;try{new RestaurantManager().start(p);}catch(Exception e){e.printStackTrace();}}
    private void start(int port)throws IOException{HttpServer s=HttpServer.create(new InetSocketAddress(port),0);s.createContext("/",this::route);s.setExecutor(Executors.newFixedThreadPool(8));s.start();System.out.println("Restaurant Control is running at http://localhost:"+port);}
    private void route(HttpExchange x)throws IOException{try{String p=x.getRequestURI().getPath(),m=x.getRequestMethod();if(m.equals("GET")&&p.equals("/"))file(x,"web/index.html","text/html; charset=utf-8");else if(m.equals("GET")&&p.equals("/app.css"))file(x,"web/app.css","text/css; charset=utf-8");else if(m.equals("GET")&&p.equals("/app.js"))file(x,"web/app.js","text/javascript; charset=utf-8");else if(m.equals("GET")&&p.equals("/api/state"))json(x,200,state());else if(m.equals("GET")&&p.equals("/api/suppliers/state"))json(x,200,supplierState());else if(m.equals("POST")&&p.equals("/api/suppliers"))saveSupplier(x);else if(m.equals("POST")&&p.equals("/api/suppliers/payment"))paySupplier(x);else if(m.equals("POST")&&p.equals("/api/sales-imports"))upload(x);else if(m.equals("POST")&&p.matches("/api/sales-imports/[^/]+/map"))remap(x,p.split("/")[3]);else if(m.equals("POST")&&p.matches("/api/sales-imports/[^/]+/confirm"))confirm(x,p.split("/")[3]);else if(m.equals("POST")&&p.equals("/api/purchase-imports"))uploadPurchase(x);else if(m.equals("POST")&&p.matches("/api/purchase-imports/[^/]+/map"))remapPurchase(x,p.split("/")[3]);else if(m.equals("POST")&&p.matches("/api/purchase-imports/[^/]+/confirm"))confirmPurchase(x,p.split("/")[3]);else if(m.equals("POST")&&p.equals("/api/waste"))waste(x);else if(m.equals("POST")&&p.equals("/api/purchases"))purchase(x);else if(m.equals("POST")&&p.equals("/api/inventory/minimum"))setMinimum(x);else json(x,404,"{\"error\":\"Not found\"}");}catch(IllegalArgumentException|IllegalStateException e){json(x,400,"{\"error\":"+q(e.getMessage())+"}");}catch(Exception e){e.printStackTrace();json(x,500,"{\"error\":\"Unexpected server error\"}");}}

    private synchronized void upload(HttpExchange x)throws Exception{Part part=multipart(x);if(part.bytes.length==0)throw new IllegalArgumentException("Choose a document");String hash=hex(MessageDigest.getInstance("SHA-256").digest(part.bytes));if(Files.exists(HASHES)&&Files.readAllLines(HASHES).contains(hash))throw new IllegalArgumentException("This document was already imported");SalesImporter.Parsed parsed=SalesImporter.parse(part.filename,part.bytes);Map<String,String> mapping=SalesImporter.detect(parsed.columns());String id=UUID.randomUUID().toString();List<SalesImporter.Row> rows=validate(SalesImporter.normalize(parsed,mapping));ImportJob job=new ImportJob(id,part.filename,hash,part.bytes,parsed,mapping,rows);staged.put(id,job);json(x,200,preview(job));}
    private synchronized void remap(HttpExchange x,String id){ImportJob old=job(id);Map<String,String> f=form(x);Map<String,String> map=new LinkedHashMap<>();for(String key:List.of("date","item","quantity","unitPrice","total","order","payment"))if(f.containsKey(key))map.put(key,f.get(key));ImportJob now=new ImportJob(old.id,old.filename,old.hash,old.original,old.parsed,map,validate(SalesImporter.normalize(old.parsed,map)));staged.put(id,now);try{json(x,200,preview(now));}catch(IOException impossible){throw new UncheckedIOException(impossible);}}
    private synchronized void confirm(HttpExchange x,String id)throws IOException{ImportJob j=job(id);if(j.rows.stream().anyMatch(r->!r.errors().isEmpty()))throw new IllegalStateException("Resolve all flagged rows before importing");Map<Inventory,Double> changes=new LinkedHashMap<>();double foodCost=0;try{for(SalesImporter.Row row:j.rows){MenuItem item=findMenu(row.item());for(Recipe.Ingredient ri:item.recipe){Inventory inv=stock.get(Inventory.key(ri.name()));double used=ri.quantity()*row.quantity();changes.merge(inv,-used,Double::sum);foodCost+=used*inv.getUnitCost();}}for(var e:changes.entrySet())e.getKey().adjust(e.getValue());}catch(Exception e){throw new IllegalStateException(e.getMessage()+". Receive stock or correct the document first.");}
        try{Files.createDirectories(IMPORTS);Files.write(IMPORTS.resolve(id+extension(j.filename)),j.original);append(HASHES,j.hash);for(SalesImporter.Row r:j.rows){MenuItem mi=findMenu(r.item());append(SALES,String.join(",",LocalDate.now().toString(),id,csv(r.date().toString()),csv(mi.name),Double.toString(r.quantity()),Double.toString(r.unitPrice()),Double.toString(r.total()),csv(r.order()),csv(r.payment())));for(Recipe.Ingredient ri:mi.recipe){double used=ri.quantity()*r.quantity();appendTx(ri.name(),"RECIPE_USAGE",-used,stock.get(Inventory.key(ri.name())).getUnitCost(),id);}}Inventory.save(STOCK,stock.values());staged.remove(id);json(x,200,"{\"message\":\"Import confirmed\",\"foodCost\":"+foodCost+"}");}catch(Exception e){for(var change:changes.entrySet())change.getKey().adjust(-change.getValue());throw e;}}
    private synchronized void waste(HttpExchange x)throws IOException{Map<String,String>f=form(x);Inventory i=ingredient(f.get("ingredient"));double amount=positive(f,"quantity");String reason=f.getOrDefault("reason","Other"),employee=f.getOrDefault("employee","").trim();i.adjust(-amount);double value=amount*i.getUnitCost();append(WASTE,String.join(",",LocalDate.now().toString(),csv(i.getName()),Double.toString(amount),csv(i.getUnit()),csv(reason),csv(employee),Double.toString(value)));appendTx(i.getName(),"WASTE",-amount,i.getUnitCost(),reason);Inventory.save(STOCK,stock.values());json(x,200,"{\"message\":\"Waste recorded\"}");}
    private synchronized void purchase(HttpExchange x)throws IOException{Map<String,String>f=form(x);Inventory i=ingredient(f.get("ingredient"));double amount=positive(f,"quantity"),cost=positive(f,"unitCost");String supplier=f.getOrDefault("supplier","");i.add(amount);i.setUnitCost(cost);appendTx(i.getName(),"PURCHASE",amount,cost,supplier);supplierStore.recordPurchase(LocalDate.now(),supplier,i.getName(),cost,amount*cost,"Manual receipt");Inventory.save(STOCK,stock.values());json(x,200,"{\"message\":\"Stock received\"}");}
    private synchronized void setMinimum(HttpExchange x)throws IOException{Map<String,String>f=form(x);Inventory i=ingredient(f.get("ingredient"));double minimum;try{minimum=Double.parseDouble(f.getOrDefault("minimum","-1"));}catch(NumberFormatException e){throw new IllegalArgumentException("Enter a valid minimum amount");}i.setReorderLevel(minimum);Inventory.save(STOCK,stock.values());json(x,200,"{\"message\":\"Minimum stock level updated\"}");}
    private synchronized void saveSupplier(HttpExchange x)throws IOException{Map<String,String>f=form(x);SupplierStore.Supplier s=new SupplierStore.Supplier(f.getOrDefault("name",""),f.getOrDefault("contact",""),f.getOrDefault("phone",""),f.getOrDefault("email",""),f.getOrDefault("address",""),f.getOrDefault("ingredients",""),f.getOrDefault("terms",""),f.getOrDefault("deliveryDays",""),number(f,"minimumOrder",0),f.getOrDefault("paymentMethod",""),f.getOrDefault("taxId",""),f.getOrDefault("status","ACTIVE"),f.getOrDefault("notes",""),percent(f,"onTime",100),percent(f,"complete",100),percent(f,"rejected",0));supplierStore.save(s);json(x,200,"{\"message\":\"Supplier saved\"}");}
    private synchronized void paySupplier(HttpExchange x)throws IOException{Map<String,String>f=form(x);supplierStore.pay(f.getOrDefault("invoiceId",""),positive(f,"amount"));json(x,200,"{\"message\":\"Supplier payment recorded\"}");}
    private static double number(Map<String,String>f,String key,double fallback){try{String s=f.getOrDefault(key,"");return s.isBlank()?fallback:Double.parseDouble(s);}catch(Exception e){throw new IllegalArgumentException("Enter a valid "+key);}}private static double percent(Map<String,String>f,String key,double fallback){double v=number(f,key,fallback);if(v<0||v>100)throw new IllegalArgumentException(key+" must be between 0 and 100");return v;}
    private String supplierState(){StringBuilder b=new StringBuilder("{\"suppliers\":[");int n=0;for(var s:supplierStore.suppliers()){if(n++>0)b.append(',');b.append("{\"name\":").append(q(s.name())).append(",\"contact\":").append(q(s.contact())).append(",\"phone\":").append(q(s.phone())).append(",\"email\":").append(q(s.email())).append(",\"address\":").append(q(s.address())).append(",\"ingredients\":").append(q(s.ingredients())).append(",\"terms\":").append(q(s.terms())).append(",\"deliveryDays\":").append(q(s.deliveryDays())).append(",\"minimumOrder\":").append(s.minimumOrder()).append(",\"paymentMethod\":").append(q(s.paymentMethod())).append(",\"taxId\":").append(q(s.taxId())).append(",\"status\":").append(q(s.status())).append(",\"notes\":").append(q(s.notes())).append(",\"onTime\":").append(s.onTime()).append(",\"complete\":").append(s.complete()).append(",\"rejected\":").append(s.rejected()).append(",\"score\":").append(s.score()).append('}');}b.append("],\"prices\":[");n=0;for(var p:supplierStore.prices()){if(n++>0)b.append(',');b.append("{\"date\":").append(q(p.date().toString())).append(",\"supplier\":").append(q(p.supplier())).append(",\"ingredient\":").append(q(p.ingredient())).append(",\"price\":").append(p.price()).append('}');}b.append("],\"invoices\":[");n=0;for(var i:supplierStore.invoices()){if(n++>0)b.append(',');b.append("{\"id\":").append(q(i.id())).append(",\"date\":").append(q(i.date().toString())).append(",\"supplier\":").append(q(i.supplier())).append(",\"reference\":").append(q(i.reference())).append(",\"amount\":").append(i.amount()).append(",\"paid\":").append(i.paid()).append(",\"balance\":").append(i.balance()).append(",\"dueDate\":").append(q(i.dueDate().toString())).append(",\"status\":").append(q(i.status())).append('}');}return b.append("]}").toString();}

    private synchronized void uploadPurchase(HttpExchange x)throws Exception{Part p=multipart(x);String hash=hex(MessageDigest.getInstance("SHA-256").digest(p.bytes));if(Files.exists(HASHES)&&Files.readAllLines(HASHES).contains(hash))throw new IllegalArgumentException("This document was already imported");var parsed=SalesImporter.parse(p.filename,p.bytes);var mapping=detectPurchase(parsed.columns());String id=UUID.randomUUID().toString();var j=new PurchaseJob(id,p.filename,hash,p.bytes,parsed,mapping,purchaseRows(parsed,mapping));stagedPurchases.put(id,j);json(x,200,purchasePreview(j));}
    private synchronized void remapPurchase(HttpExchange x,String id)throws IOException{PurchaseJob old=purchaseJob(id);Map<String,String>f=form(x),map=new LinkedHashMap<>();for(String k:List.of("date","ingredient","quantity","unitCost","total","supplier","invoice"))if(f.containsKey(k))map.put(k,f.get(k));var j=new PurchaseJob(old.id,old.filename,old.hash,old.original,old.parsed,map,purchaseRows(old.parsed,map));stagedPurchases.put(id,j);json(x,200,purchasePreview(j));}
    private synchronized void confirmPurchase(HttpExchange x,String id)throws IOException{PurchaseJob j=purchaseJob(id);if(j.rows.stream().anyMatch(r->!r.errors.isEmpty()))throw new IllegalStateException("Resolve all flagged rows before confirming");Map<Inventory,Double>qty=new LinkedHashMap<>(),costs=new LinkedHashMap<>();try{for(PurchaseRow r:j.rows){Inventory i=ingredient(r.ingredient);qty.putIfAbsent(i,i.getQuantity());costs.putIfAbsent(i,i.getUnitCost());i.add(r.quantity);i.setUnitCost(r.unitCost);}Files.createDirectories(IMPORTS);Files.write(IMPORTS.resolve("purchase-"+id+extension(j.filename)),j.original);append(HASHES,j.hash);Map<String,Double>invoiceTotals=new LinkedHashMap<>();Map<String,PurchaseRow>invoiceDetails=new HashMap<>();for(PurchaseRow r:j.rows){appendTx(r.ingredient,"PURCHASE",r.quantity,r.unitCost,r.invoice+" "+r.supplier);supplierStore.recordPrice(r.date,r.supplier,r.ingredient,r.unitCost);String key=r.supplier+"\t"+(r.invoice.isBlank()?id:r.invoice);invoiceTotals.merge(key,r.total,Double::sum);invoiceDetails.put(key,r);}for(var total:invoiceTotals.entrySet()){PurchaseRow r=invoiceDetails.get(total.getKey());supplierStore.recordInvoice(r.date,r.supplier,r.invoice.isBlank()?id:r.invoice,total.getValue());}Inventory.save(STOCK,stock.values());stagedPurchases.remove(id);json(x,200,"{\"message\":\"Purchase confirmed and inventory updated\"}");}catch(Exception e){for(var v:qty.entrySet())v.getKey().adjust(v.getValue()-v.getKey().getQuantity());for(var v:costs.entrySet())v.getKey().setUnitCost(v.getValue());throw e;}}
    private static Map<String,String> detectPurchase(List<String>cols){Map<String,String>m=new LinkedHashMap<>();for(String c:cols){String k=c.toLowerCase().replaceAll("[^a-z]","");if(k.contains("date"))m.putIfAbsent("date",c);else if(k.contains("ingredient")||k.contains("product")||k.contains("item"))m.putIfAbsent("ingredient",c);else if(k.equals("qty")||k.contains("quantity")||k.contains("received"))m.putIfAbsent("quantity",c);else if(k.contains("unitcost")||k.contains("unitprice")||k.equals("price"))m.putIfAbsent("unitCost",c);else if(k.contains("total")||k.contains("amount"))m.putIfAbsent("total",c);else if(k.contains("supplier")||k.contains("vendor"))m.putIfAbsent("supplier",c);else if(k.contains("invoice")||k.contains("reference"))m.putIfAbsent("invoice",c);}return m;}
    private List<PurchaseRow> purchaseRows(SalesImporter.Parsed parsed,Map<String,String>map){List<PurchaseRow>out=new ArrayList<>();int row=1;for(Map<String,String>raw:parsed.rawRows()){row++;List<String>e=new ArrayList<>();String name=pv(raw,map,"ingredient"),supplier=pv(raw,map,"supplier"),invoice=pv(raw,map,"invoice");double amount=pn(pv(raw,map,"quantity"),"quantity",e),cost=pn(pv(raw,map,"unitCost"),"unit cost",e),total=pn(pv(raw,map,"total"),"total",new ArrayList<>());LocalDate date;try{date=LocalDate.parse(pv(raw,map,"date"));}catch(Exception ex){date=null;e.add("Invalid date");}if(stock.get(Inventory.key(name))==null)e.add("Unknown ingredient");if(amount<=0)e.add("Quantity must be positive");if(cost<=0&&total>0&&amount>0)cost=total/amount;if(total==0&&cost>0)total=amount*cost;if(cost<=0)e.add("Unit cost must be positive");if(total>0&&Math.abs(amount*cost-total)>.02)e.add("Quantity × unit cost does not match total");out.add(new PurchaseRow(date,name,amount,cost,total,supplier,invoice,row,List.copyOf(e)));}return out;}
    private static String pv(Map<String,String>r,Map<String,String>m,String k){return r.getOrDefault(m.getOrDefault(k,""),"").trim();}private static double pn(String s,String label,List<String>e){if(s.isBlank())return 0;try{return Double.parseDouble(s.replace(",","").replaceAll("[^0-9.\\-]",""));}catch(Exception x){e.add("Invalid "+label);return 0;}}
    private String purchasePreview(PurchaseJob j){int valid=(int)j.rows.stream().filter(r->r.errors.isEmpty()).count();double total=j.rows.stream().mapToDouble(PurchaseRow::total).sum();StringBuilder b=new StringBuilder("{\"id\":").append(q(j.id)).append(",\"filename\":").append(q(j.filename)).append(",\"columns\":").append(array(j.parsed.columns())).append(",\"mapping\":{");int z=0;for(var v:j.mapping.entrySet()){if(z++>0)b.append(',');b.append(q(v.getKey())).append(':').append(q(v.getValue()));}b.append("},\"summary\":{\"rows\":").append(j.rows.size()).append(",\"valid\":").append(valid).append(",\"review\":").append(j.rows.size()-valid).append(",\"total\":").append(total).append("},\"rows\":[");for(int k=0;k<Math.min(100,j.rows.size());k++){if(k>0)b.append(',');PurchaseRow r=j.rows.get(k);b.append("{\"row\":").append(r.sourceRow).append(",\"date\":").append(q(String.valueOf(r.date))).append(",\"ingredient\":").append(q(r.ingredient)).append(",\"quantity\":").append(r.quantity).append(",\"unitCost\":").append(r.unitCost).append(",\"total\":").append(r.total).append(",\"supplier\":").append(q(r.supplier)).append(",\"errors\":").append(array(r.errors)).append('}');}return b.append("]}").toString();}
    private PurchaseJob purchaseJob(String id){PurchaseJob j=stagedPurchases.get(id);if(j==null)throw new IllegalArgumentException("Purchase preview expired; upload it again");return j;}

    private List<SalesImporter.Row> validate(List<SalesImporter.Row> rows){Set<String> orders=new HashSet<>();List<SalesImporter.Row> out=new ArrayList<>();for(var r:rows){List<String> e=new ArrayList<>(r.errors());if(findMenuOrNull(r.item())==null)e.add("Unknown menu item");if(!r.order().isBlank()&&!orders.add(r.order()))e.add("Duplicate order number in document");out.add(new SalesImporter.Row(r.date(),r.item(),r.quantity(),r.unitPrice(),r.total(),r.order(),r.payment(),r.sourceRow(),List.copyOf(e)));}return out;}
    private String preview(ImportJob j){int valid=(int)j.rows.stream().filter(r->r.errors().isEmpty()).count();double total=j.rows.stream().mapToDouble(SalesImporter.Row::total).sum();StringBuilder b=new StringBuilder("{\"id\":").append(q(j.id)).append(",\"filename\":").append(q(j.filename)).append(",\"columns\":").append(array(j.parsed.columns())).append(",\"mapping\":{");int z=0;for(var e:j.mapping.entrySet()){if(z++>0)b.append(',');b.append(q(e.getKey())).append(':').append(q(e.getValue()));}b.append("},\"summary\":{\"rows\":").append(j.rows.size()).append(",\"valid\":").append(valid).append(",\"review\":").append(j.rows.size()-valid).append(",\"total\":").append(total).append("},\"rows\":[");for(int k=0;k<Math.min(100,j.rows.size());k++){if(k>0)b.append(',');var r=j.rows.get(k);b.append("{\"row\":").append(r.sourceRow()).append(",\"date\":").append(q(String.valueOf(r.date()))).append(",\"item\":").append(q(r.item())).append(",\"quantity\":").append(r.quantity()).append(",\"total\":").append(r.total()).append(",\"errors\":").append(array(r.errors())).append('}');}return b.append("]}").toString();}
    private synchronized String state()throws IOException{double sales=0,cost=0,wasteValue=0;int records=0;if(Files.exists(SALES))for(String l:Files.readAllLines(SALES)){if(l.isBlank())continue;String[]p=l.split(",",-1);if(p.length>=7&&uncsv(p[2]).equals(LocalDate.now().toString())){records++;sales+=Double.parseDouble(p[6]);MenuItem mi=findMenuOrNull(uncsv(p[3]));if(mi!=null)for(var r:mi.recipe)cost+=r.quantity()*Double.parseDouble(p[4])*stock.get(Inventory.key(r.name())).getUnitCost();}}if(Files.exists(WASTE))for(String l:Files.readAllLines(WASTE)){String[]p=l.split(",",-1);if(p.length>=7&&p[0].equals(LocalDate.now().toString()))wasteValue+=Double.parseDouble(p[6]);}StringBuilder b=new StringBuilder("{\"today\":{\"sales\":").append(sales).append(",\"foodCost\":").append(cost).append(",\"profit\":").append(sales-cost).append(",\"waste\":").append(wasteValue).append(",\"records\":").append(records).append("},\"inventory\":[");int z=0;for(Inventory i:stock.values()){if(z++>0)b.append(',');double suggested=Math.max(0,i.getReorderLevel()-i.getQuantity());b.append("{\"name\":").append(q(i.getName())).append(",\"quantity\":").append(i.getQuantity()).append(",\"unit\":").append(q(i.getUnit())).append(",\"cost\":").append(i.getUnitCost()).append(",\"low\":").append(i.isLow()).append(",\"suggested\":").append(suggested).append('}');}b.append("],\"menu\":[");z=0;for(MenuItem m:menu.values()){if(z++>0)b.append(',');b.append("{\"name\":").append(q(m.name())).append(",\"price\":").append(m.price()).append(",\"foodCost\":").append(m.recipe().stream().mapToDouble(r->r.quantity()*stock.get(Inventory.key(r.name())).getUnitCost()).sum()).append('}');}return b.append("]}").toString();}

    private void seed()throws IOException{stock.putAll(Inventory.load(STOCK));seedIngredient("Chicken breast",8000,"g",5000,.40);seedIngredient("Burger bun",40,"piece",20,15);seedIngredient("Cheese",80,"slice",20,20);seedIngredient("Sauce",3000,"ml",800,.20);seedIngredient("Potato",12000,"g",4000,.08);seedIngredient("Cooking oil",5000,"ml",1500,.22);Inventory.save(STOCK,stock.values());addMenu("Chicken Burger",300,new Recipe.Ingredient("Chicken breast",150,"g"),new Recipe.Ingredient("Burger bun",1,"piece"),new Recipe.Ingredient("Cheese",1,"slice"),new Recipe.Ingredient("Sauce",20,"ml"));addMenu("French Fries",150,new Recipe.Ingredient("Potato",250,"g"),new Recipe.Ingredient("Cooking oil",30,"ml"));alias("chkn burger","Chicken Burger");alias("chicken burger","Chicken Burger");alias("french fries","French Fries");alias("fries","French Fries");}
    private void seedIngredient(String n,double q,String u,double low,double cost){Inventory i=stock.get(Inventory.key(n));if(i==null)stock.put(Inventory.key(n),new Inventory(n,q,u,low,cost,"",""));else if(i.getUnitCost()==0)i.setUnitCost(cost);}
    private void addMenu(String n,double p,Recipe.Ingredient...r){menu.put(Inventory.key(n),new MenuItem(n,p,List.of(r)));}private void alias(String a,String n){aliases.put(Inventory.key(a),Inventory.key(n));}
    private MenuItem findMenu(String s){MenuItem m=findMenuOrNull(s);if(m==null)throw new IllegalArgumentException("Unknown menu item: "+s);return m;}private MenuItem findMenuOrNull(String s){if(s==null)return null;String k=Inventory.key(s);return menu.getOrDefault(aliases.getOrDefault(k,k),null);}private Inventory ingredient(String s){Inventory i=stock.get(Inventory.key(s==null?"":s));if(i==null)throw new IllegalArgumentException("Unknown ingredient");return i;}
    private ImportJob job(String id){ImportJob j=staged.get(id);if(j==null)throw new IllegalArgumentException("Import preview expired; upload it again");return j;}private static double positive(Map<String,String>f,String k){try{double v=Double.parseDouble(f.getOrDefault(k,"0"));if(v<=0)throw new Exception();return v;}catch(Exception e){throw new IllegalArgumentException(k+" must be positive");}}
    private record Part(String filename,byte[]bytes){}private static Part multipart(HttpExchange x)throws IOException{String ct=x.getRequestHeaders().getFirst("Content-Type");if(ct==null||!ct.contains("boundary="))throw new IllegalArgumentException("Expected a file upload");String boundary="--"+ct.substring(ct.indexOf("boundary=")+9).replace("\"","");byte[]all=x.getRequestBody().readAllBytes();String raw=new String(all,StandardCharsets.ISO_8859_1);int name=raw.indexOf("filename=\"");if(name<0)throw new IllegalArgumentException("Choose a document");int ne=raw.indexOf('"',name+10);String filename=raw.substring(name+10,ne);int start=raw.indexOf("\r\n\r\n",ne)+4,end=raw.indexOf("\r\n"+boundary,start);return new Part(Paths.get(filename).getFileName().toString(),Arrays.copyOfRange(all,start,end));}
    private static Map<String,String>form(HttpExchange x){try{Map<String,String>m=new HashMap<>();String b=new String(x.getRequestBody().readAllBytes(),StandardCharsets.UTF_8);for(String pair:b.split("&")){String[]p=pair.split("=",2);if(p.length==2)m.put(URLDecoder.decode(p[0],StandardCharsets.UTF_8),URLDecoder.decode(p[1],StandardCharsets.UTF_8));}return m;}catch(IOException e){throw new UncheckedIOException(e);}}
    private static void appendTx(String ingredient,String type,double qty,double cost,String ref)throws IOException{append(TX,String.join(",",Instant.now().toString(),csv(ingredient),type,Double.toString(qty),Double.toString(cost),csv(ref)));}private static void append(Path p,String l)throws IOException{Files.createDirectories(p.getParent());Files.writeString(p,l+System.lineSeparator(),StandardOpenOption.CREATE,StandardOpenOption.APPEND);}private static String extension(String f){int i=f.lastIndexOf('.');return i<0?"":f.substring(i).replaceAll("[^.a-zA-Z0-9]","");}private static String hex(byte[]b){StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format("%02x",x));return s.toString();}
    private static String csv(String s){return s==null?"":"\""+s.replace("\"","\"\"")+"\"";}private static String uncsv(String s){return s.length()>=2&&s.startsWith("\"")&&s.endsWith("\"")?s.substring(1,s.length()-1).replace("\"\"","\""):s;}private static String q(String s){return "\""+(s==null?"":s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n"))+"\"";}private static String array(Collection<String>a){StringBuilder b=new StringBuilder("[");int i=0;for(String s:a){if(i++>0)b.append(',');b.append(q(s));}return b.append(']').toString();}
    private static void json(HttpExchange x,int c,String s)throws IOException{byte[]b=s.getBytes(StandardCharsets.UTF_8);x.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");x.getResponseHeaders().set("Cache-Control","no-store");x.sendResponseHeaders(c,b.length);try(OutputStream o=x.getResponseBody()){o.write(b);}}private static void file(HttpExchange x,String p,String t)throws IOException{byte[]b=Files.readAllBytes(Paths.get(p));x.getResponseHeaders().set("Content-Type",t);x.getResponseHeaders().set("Cache-Control","no-store, no-cache, must-revalidate");x.sendResponseHeaders(200,b.length);try(OutputStream o=x.getResponseBody()){o.write(b);}}
}
