import java.io.*;
import java.nio.file.*;
import java.time.*;
import java.util.*;

/** CSV-backed supplier directory, price history, delivery performance, and payables. */
public final class SupplierStore {
    public record Supplier(String name,String contact,String phone,String email,String address,String ingredients,String terms,String deliveryDays,double minimumOrder,String paymentMethod,String taxId,String status,String notes,double onTime,double complete,double rejected) {
        public double score(){return onTime*.4+complete*.4+(100-rejected)*.2;}
    }
    public record Price(LocalDate date,String supplier,String ingredient,double price) {}
    public record Invoice(String id,LocalDate date,String supplier,String reference,double amount,double paid,LocalDate dueDate) { public double balance(){return Math.max(0,amount-paid);} public String status(){if(balance()==0)return "PAID";if(paid>0)return dueDate.isBefore(LocalDate.now())?"OVERDUE":"PARTIALLY PAID";return dueDate.isBefore(LocalDate.now())?"OVERDUE":"UNPAID";} }
    private final Path suppliers,prices,invoices;
    private final Map<String,Supplier> directory=new TreeMap<>();private final List<Price> history=new ArrayList<>();private final List<Invoice> bills=new ArrayList<>();
    public SupplierStore(Path data)throws IOException{suppliers=data.resolve("suppliers.tsv");prices=data.resolve("supplier-prices.tsv");invoices=data.resolve("supplier-invoices.tsv");load();}
    public Collection<Supplier> suppliers(){return List.copyOf(directory.values());}public List<Price> prices(){return List.copyOf(history);}public List<Invoice> invoices(){return List.copyOf(bills);}
    public void save(Supplier s)throws IOException{if(s.name()==null||s.name().isBlank())throw new IllegalArgumentException("Supplier name is required");directory.put(key(s.name()),s);writeSuppliers();}
    public void ensure(String name)throws IOException{if(name==null||name.isBlank()||directory.containsKey(key(name)))return;save(new Supplier(name.trim(),"","","","","","Net 14","",0,"","","ACTIVE","",100,100,0));}
    public void recordPurchase(LocalDate date,String supplier,String ingredient,double price,double total,String reference)throws IOException{recordPrice(date,supplier,ingredient,price);recordInvoice(date,supplier,reference,total);}
    public void recordPrice(LocalDate date,String supplier,String ingredient,double price)throws IOException{if(supplier==null||supplier.isBlank())supplier="Unassigned supplier";ensure(supplier);history.add(new Price(date,supplier,ingredient,price));append(prices,date+"\t"+clean(supplier)+"\t"+clean(ingredient)+"\t"+price);}
    public void recordInvoice(LocalDate date,String supplier,String reference,double total)throws IOException{if(supplier==null||supplier.isBlank())supplier="Unassigned supplier";ensure(supplier);Invoice bill=new Invoice(UUID.randomUUID().toString(),date,supplier,reference==null?"":reference,total,0,date.plusDays(14));bills.add(bill);append(invoices,line(bill));}
    public void pay(String id,double amount)throws IOException{if(amount<=0)throw new IllegalArgumentException("Payment must be positive");for(int i=0;i<bills.size();i++){Invoice old=bills.get(i);if(old.id().equals(id)){if(amount>old.balance()+.001)throw new IllegalArgumentException("Payment exceeds the remaining balance");bills.set(i,new Invoice(old.id(),old.date(),old.supplier(),old.reference(),old.amount(),old.paid()+amount,old.dueDate()));writeInvoices();return;}}throw new IllegalArgumentException("Invoice not found");}
    private void load()throws IOException{if(Files.exists(suppliers))for(String l:Files.readAllLines(suppliers)){String[]p=l.split("\t",-1);if(p.length>=16){Supplier s=new Supplier(p[0],p[1],p[2],p[3],p[4],p[5],p[6],p[7],num(p[8]),p[9],p[10],p[11],p[12],num(p[13]),num(p[14]),num(p[15]));directory.put(key(s.name()),s);}}if(Files.exists(prices))for(String l:Files.readAllLines(prices)){String[]p=l.split("\t",-1);if(p.length>=4)history.add(new Price(LocalDate.parse(p[0]),p[1],p[2],num(p[3])));}if(Files.exists(invoices))for(String l:Files.readAllLines(invoices)){String[]p=l.split("\t",-1);if(p.length>=7)bills.add(new Invoice(p[0],LocalDate.parse(p[1]),p[2],p[3],num(p[4]),num(p[5]),LocalDate.parse(p[6])));}}
    private void writeSuppliers()throws IOException{List<String>ls=new ArrayList<>();for(Supplier s:directory.values())ls.add(String.join("\t",clean(s.name()),clean(s.contact()),clean(s.phone()),clean(s.email()),clean(s.address()),clean(s.ingredients()),clean(s.terms()),clean(s.deliveryDays()),String.valueOf(s.minimumOrder()),clean(s.paymentMethod()),clean(s.taxId()),clean(s.status()),clean(s.notes()),String.valueOf(s.onTime()),String.valueOf(s.complete()),String.valueOf(s.rejected())));write(suppliers,ls);}
    private void writeInvoices()throws IOException{List<String>ls=new ArrayList<>();for(Invoice i:bills)ls.add(line(i));write(invoices,ls);}private static String line(Invoice i){return String.join("\t",i.id(),i.date().toString(),clean(i.supplier()),clean(i.reference()),String.valueOf(i.amount()),String.valueOf(i.paid()),i.dueDate().toString());}
    private static void write(Path p,List<String>ls)throws IOException{Files.createDirectories(p.getParent());Files.write(p,ls);}private static void append(Path p,String s)throws IOException{Files.createDirectories(p.getParent());Files.writeString(p,s+System.lineSeparator(),StandardOpenOption.CREATE,StandardOpenOption.APPEND);}private static String clean(String s){return s==null?"":s.replace('\t',' ').replace('\n',' ');}private static String key(String s){return s.trim().toLowerCase(Locale.ROOT);}private static double num(String s){try{return Double.parseDouble(s);}catch(Exception e){return 0;}}
}
