const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),etb=n=>`${new Intl.NumberFormat().format(Math.round(n||0))} ETB`;let state,supplierState={suppliers:[],prices:[],invoices:[]},current,currentPurchase;
async function load(){let [r,s]=await Promise.all([fetch('/api/state'),fetch('/api/suppliers/state')]);state=await r.json();supplierState=await s.json();render();renderSuppliers()}
function render(){let t=state.today,pct=t.sales?t.foodCost/t.sales*100:0;$('#date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase();$('#sales').textContent=$('#rSales').textContent=etb(t.sales);$('#cost').textContent=$('#rCost').textContent=etb(t.foodCost);$('#profit').textContent=$('#rProfit').textContent=etb(t.profit);$('#wasteValue').textContent=$('#rWaste').textContent=etb(t.waste);$('#costPct').textContent=`${pct.toFixed(1)}% of sales`;
  let low=state.inventory.filter(i=>i.low);$('#lowList').innerHTML=low.length?low.slice(0,5).map(i=>`<div class="low-item"><span>${i.name}</span><small>${i.quantity.toFixed(1)} ${i.unit} on hand</small><b>Buy ${i.suggested.toFixed(1)} ${i.unit}</b></div>`).join(''):'<p>Everything is above its minimum level.</p>';
  $('#stockRows').innerHTML=state.inventory.map(i=>`<tr><td><b>${i.name}</b></td><td>${i.quantity.toFixed(2)} ${i.unit}</td><td>${i.cost.toFixed(2)} ETB / ${i.unit}</td><td><span class="badge ${i.low?'low':''}">${i.low?'Reorder':'Sufficient'}</span></td><td>${i.suggested?`${i.suggested.toFixed(1)} ${i.unit}`:'—'}</td></tr>`).join('');
  $$('.ingredients').forEach(s=>s.innerHTML=state.inventory.map(i=>`<option>${i.name}</option>`).join(''));$('#minimumIngredient').innerHTML=state.inventory.map(i=>`<option>${i.name}</option>`).join('');updateMinimumUnit();$('#menuRows').innerHTML=state.menu.map(m=>`<tr><td><b>${m.name}</b></td><td>${etb(m.price)}</td><td>${etb(m.foodCost)}</td><td>${(m.foodCost/m.price*100).toFixed(1)}%</td></tr>`).join('')}
function go(id){$$('nav button,.view').forEach(x=>x.classList.remove('active'));document.querySelector(`[data-view="${id}"]`)?.classList.add('active');$('#'+id).classList.add('active');$('#title').textContent=document.querySelector(`[data-view="${id}"] span`)?.textContent||'Sales import'}
$$('nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('.uploadJump').forEach(b=>b.onclick=()=>go('import'));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
async function post(url,data,multipart=false){let r=await fetch(url,{method:'POST',headers:multipart?{}:{'Content-Type':'application/x-www-form-urlencoded'},body:multipart?data:new URLSearchParams(data)}),text=await r.text(),out;try{out=JSON.parse(text)}catch(e){throw Error(r.status===404?'The running server is outdated. Stop it, recompile, and restart.':'The server returned an invalid response. Restart the app and try again.')}if(!r.ok)throw Error(out.error||`Upload failed (${r.status})`);return out}
$('#uploadForm').onsubmit=async e=>{e.preventDefault();try{current=await post('/api/sales-imports',new FormData(e.target),true);showPreview()}catch(x){toast(x.message,true)}};
$('#purchaseUploadForm').onsubmit=async e=>{e.preventDefault();try{currentPurchase=await post('/api/purchase-imports',new FormData(e.target),true);showPurchasePreview()}catch(x){toast(x.message,true)}};
function showPreview(){let fields={date:'Sale date',item:'Menu item',quantity:'Quantity',unitPrice:'Unit price',total:'Sales amount',order:'Order number',payment:'Payment method'};$('#preview').innerHTML=`<div class="panel"><div class="preview-head"><div><p class="kicker">IMPORT PREVIEW</p><h3>${current.filename}</h3></div><button id="confirm" class="primary" ${current.summary.review?'disabled':''}>Confirm import</button></div><div class="summary"><span><b>${current.summary.rows}</b>Rows found</span><span><b>${current.summary.valid}</b>Valid</span><span><b>${current.summary.review}</b>Need review</span><span><b>${etb(current.summary.total)}</b>Total sales</span></div><p><b>Column mapping</b> — check what we detected.</p><form id="mapForm" class="mapping">${Object.entries(fields).map(([k,v])=>`<label>${v}<select name="${k}"><option value="">Not provided</option>${current.columns.map(c=>`<option ${current.mapping[k]===c?'selected':''}>${c}</option>`).join('')}</select></label>`).join('')}<button class="primary">Apply mapping</button></form><div class="table-wrap"><table><thead><tr><th>Row</th><th>Date</th><th>Menu item</th><th>Quantity</th><th>Sales</th><th>Validation</th></tr></thead><tbody>${current.rows.map(r=>`<tr><td>${r.row}</td><td>${r.date}</td><td>${r.item}</td><td>${r.quantity}</td><td>${etb(r.total)}</td><td>${r.errors.length?`<span class="error">${r.errors.join(' · ')}</span>`:'<span class="badge">Ready</span>'}</td></tr>`).join('')}</tbody></table></div></div>`;$('#mapForm').onsubmit=async e=>{e.preventDefault();try{current=await post(`/api/sales-imports/${current.id}/map`,Object.fromEntries(new FormData(e.target)));showPreview()}catch(x){toast(x.message,true)}};$('#confirm').onclick=async()=>{try{let out=await post(`/api/sales-imports/${current.id}/confirm`,{});toast(out.message);$('#preview').innerHTML='';await load();go('today')}catch(x){toast(x.message,true)}}}
function showPurchasePreview(){let fields={date:'Delivery date',ingredient:'Ingredient',quantity:'Quantity received',unitCost:'Unit cost',total:'Line total',supplier:'Supplier',invoice:'Invoice number'},p=currentPurchase;$('#purchasePreview').innerHTML=`<div class="panel"><div class="preview-head"><div><p class="kicker">PURCHASE PREVIEW</p><h3>${p.filename}</h3></div><button id="confirmPurchase" class="primary" ${p.summary.review?'disabled':''}>Confirm & update stock</button></div><div class="summary"><span><b>${p.summary.rows}</b>Lines found</span><span><b>${p.summary.valid}</b>Valid</span><span><b>${p.summary.review}</b>Need review</span><span><b>${etb(p.summary.total)}</b>Purchase total</span></div><p><b>Column mapping</b> — confirm the supplier’s headings.</p><form id="purchaseMapForm" class="mapping">${Object.entries(fields).map(([k,v])=>`<label>${v}<select name="${k}"><option value="">Not provided</option>${p.columns.map(c=>`<option ${p.mapping[k]===c?'selected':''}>${c}</option>`).join('')}</select></label>`).join('')}<button class="primary">Apply mapping</button></form><div class="table-wrap"><table><thead><tr><th>Row</th><th>Date</th><th>Ingredient</th><th>Quantity</th><th>Unit cost</th><th>Total</th><th>Supplier</th><th>Validation</th></tr></thead><tbody>${p.rows.map(r=>`<tr><td>${r.row}</td><td>${r.date}</td><td>${r.ingredient}</td><td>${r.quantity}</td><td>${r.unitCost} ETB</td><td>${etb(r.total)}</td><td>${r.supplier||'—'}</td><td>${r.errors.length?`<span class="error">${r.errors.join(' · ')}</span>`:'<span class="badge">Ready</span>'}</td></tr>`).join('')}</tbody></table></div></div>`;$('#purchaseMapForm').onsubmit=async e=>{e.preventDefault();try{currentPurchase=await post(`/api/purchase-imports/${p.id}/map`,Object.fromEntries(new FormData(e.target)));showPurchasePreview()}catch(x){toast(x.message,true)}};$('#confirmPurchase').onclick=async()=>{try{let out=await post(`/api/purchase-imports/${p.id}/confirm`,{});toast(out.message);$('#purchasePreview').innerHTML='';$('#purchaseUploadForm').reset();await load();go('inventory')}catch(x){toast(x.message,true)}}}
for(let [id,url] of [['wasteForm','/api/waste'],['purchaseForm','/api/purchases']])$('#'+id).onsubmit=async e=>{e.preventDefault();try{let out=await post(url,Object.fromEntries(new FormData(e.target)));toast(out.message);e.target.reset();await load()}catch(x){toast(x.message,true)}};
function renderSuppliers(){let s=supplierState.suppliers,i=supplierState.invoices,p=supplierState.prices;$('#supplierCount').textContent=s.length;$('#amountOwed').textContent=etb(i.reduce((a,x)=>a+x.balance,0));$('#overdueCount').textContent=i.filter(x=>x.status==='OVERDUE').length;$('#priceCount').textContent=p.length;$('#supplierCards').innerHTML=s.length?s.map(x=>`<article class="panel"><div class="panel-head"><div><p class="kicker">${x.status}</p><h3>${x.name}</h3></div><span class="badge ${x.score<75?'low':''}">${x.score.toFixed(0)}% score</span></div><p>${x.ingredients||'No ingredients listed'}</p><small>${x.contact||'No contact'} · ${x.phone||x.email||'No contact details'}</small><hr><p>On time <b>${x.onTime}%</b> · Complete <b>${x.complete}%</b> · Rejected <b>${x.rejected}%</b></p><button class="editSupplier" data-name="${x.name}">Edit</button></article>`).join(''):'<div class="empty">Add your first supplier, or confirm a purchase document to create one automatically.</div>';$('#invoiceRows').innerHTML=i.length?i.slice().reverse().map(x=>`<tr><td><b>${x.supplier}</b></td><td>${x.reference||'—'}</td><td>${x.dueDate}</td><td>${etb(x.amount)}</td><td>${etb(x.paid)}</td><td><b>${etb(x.balance)}</b></td><td><span class="badge ${x.status==='OVERDUE'?'low':''}">${x.status}</span></td><td>${x.balance?`<button class="payInvoice" data-id="${x.id}" data-balance="${x.balance}" data-label="${x.supplier} — ${x.reference}">Pay</button>`:''}</td></tr>`).join(''):'<tr><td colspan="8">No supplier invoices yet.</td></tr>';$('#priceRows').innerHTML=p.length?p.slice().reverse().map(x=>`<tr><td>${x.date}</td><td>${x.supplier}</td><td><b>${x.ingredient}</b></td><td>${x.price.toFixed(2)} ETB</td></tr>`).join(''):'<tr><td colspan="4">Prices appear after receiving purchases.</td></tr>';$$('.editSupplier').forEach(b=>b.onclick=()=>openSupplier(s.find(x=>x.name===b.dataset.name)));$$('.payInvoice').forEach(b=>b.onclick=()=>{let f=$('#paymentForm');f.invoiceId.value=b.dataset.id;f.amount.max=b.dataset.balance;f.amount.value=b.dataset.balance;$('#paymentInvoice').textContent=`${b.dataset.label} · Remaining ${etb(b.dataset.balance)}`;$('#paymentDialog').showModal()})}
function openSupplier(s){let f=$('#supplierForm');f.reset();if(s)for(let [k,v]of Object.entries(s))if(f.elements[k])f.elements[k].value=v;$('#supplierDialog').showModal()}
$('#newSupplier').onclick=()=>openSupplier();$$('#supplierDialog .dialog-close').forEach(b=>b.onclick=()=>$('#supplierDialog').close());$$('#paymentDialog .dialog-close').forEach(b=>b.onclick=()=>$('#paymentDialog').close());
$('#supplierForm').onsubmit=async e=>{e.preventDefault();try{let out=await post('/api/suppliers',Object.fromEntries(new FormData(e.target)));toast(out.message);$('#supplierDialog').close();await load()}catch(x){toast(x.message,true)}};
$('#paymentForm').onsubmit=async e=>{e.preventDefault();try{let out=await post('/api/suppliers/payment',Object.fromEntries(new FormData(e.target)));toast(out.message);$('#paymentDialog').close();await load()}catch(x){toast(x.message,true)}};
function toast(s,error=false){let t=$('#toast');t.textContent=s;t.className=`show ${error?'error':''}`;setTimeout(()=>t.className='',3000)}load().catch(()=>toast('Cannot reach the local server',true));
function updateMinimumUnit(){let i=state?.inventory.find(x=>x.name===$('#minimumIngredient').value);$('#minimumUnit').textContent=i?`Measured in ${i.unit}`:''}
$('#setMinimumButton').onclick=()=>$('#minimumDialog').showModal();$('#closeMinimum').onclick=()=>$('#minimumDialog').close();$('#minimumIngredient').onchange=updateMinimumUnit;
$('#minimumForm').onsubmit=async e=>{e.preventDefault();try{let out=await post('/api/inventory/minimum',Object.fromEntries(new FormData(e.target)));toast(out.message);$('#minimumDialog').close();e.target.reset();await load()}catch(x){toast(x.message,true)}};
